{
 "title": "IBM DB2 Database - DB Stats",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "db",
    "label": "DB",
    "query": "show tag values from \"snapdb\" with key=\"db\""
   }
  ]
 },
 "panels": [
  {
   "title": "$db",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "db",
   "collapsed": true,
   "panels": [
    {
     "title": "Active Log Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "log_util",
       "select": [
        [
         { "params": [ "log_util_percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "last",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snapdb",
       "select": [
        [
         { "params": [ "locks_waiting" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Lock-wait" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      },
      {
       "alias": "last",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snapdb",
       "select": [
        [
         { "params": [ "num_indoubt_trans" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Indoubt" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Bufferpool Hit Ratio in %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_bp",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "bp" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "bp_util",
       "select": [
        [
         { "params": [ "hit_ratio_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Tablespaces Utilization",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_tbsp_name",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "tbsp_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tbsp_util",
       "select": [
        [
         { "params": [ "tbsp_util_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Indoubt Transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "last",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snapdb",
       "query": "SELECT last(\"num_indoubt_trans\") FROM \"snapdb\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY time(5m) fill(null)",
       "select": [
        [
         { "params": [ "num_indoubt_trans" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Lock-wait Transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "last",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snapdb",
       "select": [
        [
         { "params": [ "locks_waiting" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Connections",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "snapdb",
       "query": "SELECT mean(\"appls_cur_cons\") FROM \"snapdb\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "appls_cur_cons" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Active Appls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_appl_name",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "appl_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snapappl",
       "query": "select mean(count_my_cost) from (SELECT count(\"my_cost\") as count_my_cost FROM \"snapappl\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"appl_name\", time(5m)) GROUP BY time($inter), \"appl_name\" fill(null)",
       "select": [
        [
         { "params": [ "my_cost" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Active Logs Utilization - $db",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "Log_util",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "db" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "log_util",
       "select": [
        [
         { "params": [ "log_util_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Archived Logs - previous 1 hour - $db",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "last",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "datax1h",
       "select": [
        [
         { "params": [ "arch_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Dynamic+Static SQLs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Dynamic",
       "groupBy": [
        { "params": [ "db" ], "type": "tag" }
       ],
       "measurement": "snapdb2",
       "query": "select mean(\"non_negative_difference\") from (SELECT non_negative_difference(\"dynamic_sql\") FROM \"snapdb2\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter) GROUP BY time($inter)",
       "select": [
        [
         { "params": [ "commit_sql" ], "type": "field" },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      },
      {
       "alias": "Static",
       "groupBy": [
        { "params": [ "db" ], "type": "tag" }
       ],
       "measurement": "snapdb2",
       "query": "select mean(\"non_negative_difference\") from (SELECT non_negative_difference(\"static_sql\") FROM \"snapdb2\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter) GROUP BY time($inter)",
       "select": [
        [
         { "params": [ "rollback_sql" ], "type": "field" },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Commit+Rollback SQLs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Commit",
       "groupBy": [
        { "params": [ "db" ], "type": "tag" }
       ],
       "measurement": "snapdb2",
       "query": "select mean(\"non_negative_difference\") from (SELECT non_negative_difference(\"commit_sql\") FROM \"snapdb2\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter) GROUP BY time($inter)",
       "select": [
        [
         { "params": [ "commit_sql" ], "type": "field" },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      },
      {
       "alias": "Rollback",
       "groupBy": [
        { "params": [ "db" ], "type": "tag" }
       ],
       "measurement": "snapdb2",
       "query": "select mean(\"non_negative_difference\") from (SELECT non_negative_difference(\"rollback_sql\") FROM \"snapdb2\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter) GROUP BY time($inter)",
       "select": [
        [
         { "params": [ "rollback_sql" ], "type": "field" },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Top 5 Appls - CPU Time",
     "type": "table",
     "description": "Critical > 900s, Interval=5m",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snapappl",
       "query": "select agent_id, appl_name, client_ip, auth_id, exec_id, TOP(diff_usr_cpu_time_s,5) as cpu_time from (SELECT (non_negative_difference(/usr_cpu_time_s|sys_cpu_time_s/)) as diff FROM \"snapappl\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter group by agent_id, appl_name, client_ip, auth_id, exec_id)",
       "select": [
        [
         { "params": [ "appl_id" ], "type": "field" }
        ],
        [
         { "params": [ "appl_name" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Appls - CPU Time",
     "type": "graph",
     "description": "Critical > 900s, Interval = auto, cpu_time > 60s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_appl_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT MEAN(diff_usr_cpu_time_s) as usr_cpu_time_mean FROM (SELECT (non_negative_difference(/usr_cpu_time_s|sys_cpu_time_s/)) as diff FROM \"snapappl\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"agent_id\", \"appl_name\", \"appl_id\", \"auth_id\") WHERE diff_usr_cpu_time_s > 60 GROUP BY time($inter), \"appl_name\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 5 Appls - Highest Query-Cost",
     "type": "table",
     "description": "critical > 10000000, Query-Cost = Rows_Read / Rows_Selected",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent_id" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snapappl",
       "query": "SELECT \"agent_id\", \"appl_name\", \"rows_read\", \"rows_selected\", TOP(max_cost,5) as cost FROM (SELECT MAX(my_cost) as max_cost, \"appl_name\", \"rows_read\", \"rows_selected\" FROM \"snapappl\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"agent_id\")",
       "select": [
        [
         { "params": [ "(rows_read/rows_selected)" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Appls - High Query-Cost",
     "type": "graph",
     "description": "Interval = auto, critical > 10000000, cost > 1000, Query-Cost = Rows_Read / Rows_Selected",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "alias": "$tag_appl_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT MEAN(\"my_cost\") FROM \"snapappl\" WHERE (\"db\" =~ /^$db$/) AND \"my_cost\" > 1000 AND $timeFilter GROUP BY time($inter), \"appl_name\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top 5 Appls - Long Running SQL",
     "type": "table",
     "description": "critical > 10000000",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent_id" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snapappl",
       "query": "SELECT \"appl_handle\", \"appl_name\", \"auth_id\", TOP(max_elapsed_time_sec,5) as elapsed_time, \"stmt_text\" FROM (SELECT MAX(elapsed_time_sec) as max_elapsed_time_sec ,\"appl_handle\", \"appl_name\",\"stmt_text\"  FROM \"longsql\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"appl_name\",\"auth_id\")",
       "select": [
        [
         { "params": [ "(rows_read/rows_selected)" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Appls - Long Running SQL",
     "type": "graph",
     "description": "Interval = auto, critical > 30 min",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s", "label": "Elapsed Time" }
     ],
     "targets": [
      {
       "alias": "$tag_appl_name",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "appl_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "longsql",
       "select": [
        [
         { "params": [ "elapsed_time_sec" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Users Connected in Heatmap($inter)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "targets": [
      {
       "alias": "$tag_auth_id",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "auth_id" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snapappl",
       "query": "select mean(count_my_cost) from (SELECT count(\"my_cost\") as count_my_cost FROM \"snapappl\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"auth_id\", time(5m) ) GROUP BY time($inter), \"auth_id\" fill(null)",
       "select": [
        [
         { "params": [ "my_cost" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "db", "operator": "=~", "value": "/^$db$/" }
       ]
      }
     ]
    },
    {
     "title": "Users Connected in Histogram($inter)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "alias": "$tag_auth_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT MEAN(user_count) FROM (SELECT count(\"my_cost\") as user_count FROM \"snapappl\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY time(5m), \"auth_id\") GROUP BY time($inter), \"auth_id\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}