{
 "title": "IBM DB2 Database - Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "db",
    "label": "DB",
    "query": "show tag values from \"snapdb\" with key=\"db\""
   }
  ]
 },
 "panels": [
  { "title": "DBs Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections - $db",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snapdb",
     "select": [
      [
       { "params": [ "appls_cur_cons" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Bufferpool Hit Ratio($inter) - $db",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$tag_bp ($tag_db)",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "bp" ], "type": "tag" }
     ],
     "measurement": "bp_util",
     "query": "SELECT MEAN(diff) from (SELECT non_negative_difference(\"rows_read\") as diff FROM \"snapdb2\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"db\") GROUP BY time($inter), \"db\" fill(none)",
     "select": [
      [
       { "params": [ "hit_ratio_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Indoubt Transactions($inter) - $db",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snapdb",
     "select": [
      [
       { "params": [ "num_indoubt_trans" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Lock-wait Transactions($inter) - $db",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snapdb",
     "select": [
      [
       { "params": [ "locks_waiting" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Logs Utilization - $db",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "log_util",
     "select": [
      [
       { "params": [ "log_util_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Archived Logs - previous 1 hour - $db",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Number of Files" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "datax1h",
     "select": [
      [
       { "params": [ "arch_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Rollback SQLs - $db",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "db" ], "type": "tag" }
     ],
     "measurement": "snapdb2",
     "query": "SELECT MEAN(diff) from (SELECT non_negative_difference(\"rollback_sql\") as diff FROM \"snapdb2\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"db\") GROUP BY time($inter), \"db\" fill(none)",
     "select": [
      [
       { "params": [ "rollback_sql" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Rows Read - $db",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "db" ], "type": "tag" }
     ],
     "measurement": "snapdb2",
     "query": "SELECT MEAN(diff) from (SELECT non_negative_difference(\"rows_read\") as diff FROM \"snapdb2\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"db\") GROUP BY time($inter), \"db\" fill(none)",
     "select": [
      [
       { "params": [ "rows_read" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Dynamic SQLs - $db",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "db" ], "type": "tag" }
     ],
     "measurement": "snapdb2",
     "query": "SELECT MEAN(diff) from (SELECT non_negative_difference(\"dynamic_sql\") as diff FROM \"snapdb2\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"db\") GROUP BY time($inter), \"db\" fill(none)",
     "select": [
      [
       { "params": [ "dynamic_sql" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Commit SQLs - $db",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "db" ], "type": "tag" }
     ],
     "measurement": "snapdb2",
     "query": "SELECT MEAN(diff) from (SELECT non_negative_difference(\"commit_sql\") as diff FROM \"snapdb2\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"db\") GROUP BY time($inter), \"db\" fill(none)",
     "select": [
      [
       { "params": [ "commit_sql" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Tablespace Used Space - $db",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$tag_tbsp_name",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "tbsp_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tbsp_util",
     "select": [
      [
       { "params": [ "tbsp_used_kb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Static SQLs - $db",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "db" ], "type": "tag" }
     ],
     "measurement": "snapdb2",
     "query": "SELECT MEAN(diff) from (SELECT non_negative_difference(\"static_sql\") as diff FROM \"snapdb2\" WHERE (\"db\" =~ /^$db$/) AND $timeFilter GROUP BY \"db\") GROUP BY time($inter), \"db\" fill(none)",
     "select": [
      [
       { "params": [ "static_sql" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  }
 ]
}